[[redirects]]
  from = "/api/*"
  to = "https://cars-by-api-ninjas.p.rapidapi.com/v1/:splat"
  status = 200
  force = true
  headers = { 
    "X-RapidAPI-Key" = "YOUR_KEY",
    "X-RapidAPI-Host" = "cars-by-api-ninjas.p.rapidapi.com" 
  }
  